### ISSUE TITLE
Implement 3D Hull

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#133]
An implementation based in gl-vec3 points.

https://www.npmjs.com/package/quickhull3d

https://github.com/jscad/OpenJSCAD.org/issues/226

**Comment by kaosat-dev** [comment]
@z3dev that is a good one (I checked it out and experimented with it around a year ago).
- Internally it uses half edge data structures (the main alternative geometric implementation I mentioned a few times for ...V3 ? :)
- it sadly has a very big set of dependencies (at least as far as I remember)
- still worth digging into at some point imho

**Comment by hg42** [comment]
btw. apart from being a newbie in node.js, I am also new to jscad (having used openscad with a python wrapper for several years). That's why I really need the hull function.

**Comment by z3dev** [comment]
@hg42 Cool!

@kaosat-dev and I are hashing out the guts of V2 now, and it looks like we are coming to a great plan. Hold on for a week or two. We should have something more stable to work with. All comments on V2 are also welcome. 😃

**Comment by hg42** [comment]
it's working now (first 3D tests) in cli and web, using csg master branch.
I didn't check desktop, but it uses an older csg anyways (why?)

**Comment by hg42** [comment]
![image](https://user-images.githubusercontent.com/4707597/51246537-f2ba7d00-198a-11e9-9b19-c579d7a546ee.png)

**Comment by z3dev** [comment]
@hg42 Wow! That was fast! Awesome!

Basically, everything released is using the V1 CSG library at this time. So, your results (if based on the previous work) should work fine.

HOWEVER...

What we really want...
- something that we own and maintain (dependencies NONE)
- something that works with V2 solids (geometry)
- something that can be represented via the API (declarative)

So, please dig deeply into V2. And let us know if the quickhull3D is compatible.

Again, this is a little early. But we are making some progress on V2.

**Comment by hg42** [comment]
Do you mean rewriting quickhull3d with jscad data structures and embedding it?
Or copying the necessary files?
Or to browserify the package like @jallwine did?

> something that we own and maintain (dependencies NONE)

hmm, I am a big fan of using modules and collaborating.
In most cases the creator of a module will be the one who knows best how it works and how it can evolve and how it should be maintained.
If you try to maintain it yourself, you are duplicating his work and you usually don't reach the expert level of the original creator.
There are certainly algorithms that have an optimal implementation, no bugs and will not change. Like mathematics.

> something that works with V2 solids (geometry)

the hull() function has the same interface as before. Or do you mean the quickhull3d function?
I am currently not aware what is special with V2 solids. I can take a look and try to understand what you might mean.

> something that can be represented via the API (declarative)

not sure what you mean here... the hull() function is a relatively small wrapper around quickhull3d, simply converting the data structures to pure arrays. This is a small overhead compared to what runs inside the function, the internal use of simpler structures might even be faster. But I don't know, this would have to be evaluated.

btw. chain_hull also works out of the box, because it doesn't check the type (which is the correct way):

![image](https://user-images.githubusercontent.com/4707597/51251911-b4c55500-199a-11e9-8b75-ae75535a7fd7.png)

**Comment by kaosat-dev** [comment]
@hg42 that was really fast, kudos ! 
To expand a bit on what @z3dev said:
- for now csg.js has zero dependencies, and *as much as possible* we would like to keep the number of dependencies close to zero (unless a dependency has a huge benefit): I agree about specialized dependencies and their quality, unfortunately the indirect dependencies tend to turn that into a problem. 
- desktop: that is a mistake, but again the 'inbetween' status above makes it hard to maintain all.
- V2 is still an early work in progress but a LOT of things are changing, and unfortunately right now we are in an in-between state where things are still messy , and we have 'frozen' V1 because we just do not have the time to maintain two versions, and V1 has too many fundamental problems to continue as such. 
It means we will not add any more code or do releases for V1 : however I am very curious about how you implemented the bridge between csg & quickHull3d as `quickHull3D` uses half edge data structures which is the most likely candidate for future internal geometric formats for jscad (we discussed this a bit with other people from the stack.gl/regl community)

**Comment by hg42** [comment]
thanks, but the work was already done before, by @jallwine and my own binding, I only had to adapt it to changes in data structures etc.
Fortunately I had done the same myself for 3D and 2D was already there.

I know (because I see) that everything is in flux for V2.
Despite of that I would like to have a running csg V2 for testing and investigating.
Partly to continue with hull3d on V2 (it's partly ready). And also to look deeper into V2 (learning by doing).

However, currently it doesn't run in cli, because of an error (if using V2 branch of both repos):
`Error: Cannot find module './primitives3d-api'`
and web shows the same.

Are you already using the V2 code (even if incomplete)?
If "no", then no problem, I will wait.
if "yes", could you tell me which combination of branches/commits of OpenJSCAD.org and csg.js you are using which work for you?
Additionally, which package are you using for testing? cli, web? (I guess not desktop)
I mainly use cli (creating stl, displaying in an independent viewer), and web (currently displaying the jscad file via npm run dev).

I am asking because my setup could be wrong or I am doing something wrong, e.g. because my knowledge about node.js and tools is still limited.
Usually I check out a working repo, try to become familiar with it and test it for a while and then start my own changes. This way I am mostly sure it's my fault.
So, I want to start with a known working state that includes csg V2.

**Comment by khjde1207** [comment]
I will cheer.
will wait.
Please add features!!!

**Comment by z3dev** [comment]
We love fans! Thanks, @khjde1207

**Comment by pentacular** [comment]
I put together my own quickhull a while back.
The approach I used was to generate a point cloud and hull that.
It was also simpler for me, since I use jscad as a library, so I could easily use quickhull as an external dependency.

The nice thing about a point cloud is that you can convert both 2d and 3d shapes to point clouds, translate, rotate, etc, then union, and then hull those together.

(Assuming that point clouds were a V2 geometry, that is)

**Comment by hg42** [comment]
@pentacular yes, my pull request also extracts a point cloud from the objects. Mainly because it's the data quickhull expects.
That's one of the reasons I asked for a stable API for the basic types, like points, lines, in 2D, 3D, etc.
It should also allow to extract points from objects, lines from objects, etc.

**Comment by pentacular** [comment]
Yes, I think that's exactly right.

We need a set of geometries, which support operations like union, intersection, difference, transform, and a set of interchange representations which geometries can produce and be produced from.

Then perhaps we can support quickhull as a dependency of a model rather than of csg.

**Comment by pentacular** [comment]
I've put together a design showing how we might get this done, and put in a number of PRs in this direction.

The doc is available here -- feel free to comment or edit (they'll show up as suggestions)
https://docs.google.com/document/d/1nz7dhtErHBqBpuFcu7ooRU91miVTD4UxiJ6od1TbUgs/edit#

Hull should be implementable as a transformation of interchange formats.

e.g., geometries -> point arrays -> hull() -> polygon array -> geometry

It should also be possible to drop in user defined geometries.

And things like conversion functions can work the same way

geometry -> polygon array -> conversion() -> encoded string.

Please let me know what you think :)

**Comment by z3dev** [comment]
V2 now includes hull for 3D geometries, using quickhull.

I’m closing this issue as the general discussion has been resolved.
Specific issues can be opened against V2 OpenJSCAD.org.
