### ISSUE TITLE
Performance: CSG.Vector3D()

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#24]
_From @z3dev on November 28, 2015 7:24_

This is just an observation about CSG.Vector3D(x,y,z)

It seems that this is the work horse of CSG internals, converting from "points", arrays, integers, etc. Although good for usability, this function could be partitioned into smaller functions to improve performance. For example, CSG.Vector3D.fromPoint(point) or CSG.Vector3D.fromObject(object), or CSG.Vector3D.fromCoordiatest(x,y,z), etc.

It looks that CSG.Vector3D.Create(x,y,z) has started this process. I think there's even more improvement possible when the 'type" of the argument is known.

_Copied from original issue: joostn/OpenJsCad#75_

**Comment by jeromew** [comment]
+1 duck-typing in the constructors (trying to clean & discover the arguments) should be removed as a global rule for optimization. API must exist to do the checks but at the boundary of CAG/CSG operations otherwise we keep validating things over and over again.

**Comment by jeromew** [comment]
the code of glMatrix http://glmatrix.net/docs/vec3.js is interesting. Note that our "Create" is called "fromValues" and that their base API is array-compatible, probably because webGL prefers arrays. Vec3 are [x,y,z]

Threejs has made another choice https://github.com/mrdoob/three.js/blob/master/src/math/Vector3.js  with Vec3 as {x:,y:,z:}. I would have thought that this is slower than working with arrays so I am a bit surprised.

This slideshow is interesting http://media.tojicode.com/sfjs-vectors/ it was written by the author of glmatrix and basically states that in a project like csg.js it is very important to be careful to the frequency of object creation and to the choice of how points are stored.

glmatrix works both browser side and server side. Nevertheless, browser gl optimization seem to be based on SIMD.js which chrome abandoned (cf https://www.chromestatus.com/feature/5757910432874496) (it still exists in firefox). So it maybe is not the web-gl silver bullet that I thought it was. Reading https://bugs.chromium.org/p/v8/issues/detail?id=4124 it is not even clear to me if wasm would increase the speed of openjscad calculations.

The API of glmatrix is interesting optimisation-wise (avoiding object creation when possible).

In CSG.js a lot of objects are created during csg operations (plane intersections) and I saw that there was a refactoring regarding immutability (am i correct) to fix some bugs (?)

**Comment by jeromew** [comment]
https://news.ycombinator.com/item?id=14479166 - 	Google removes SIMD.js support from Chromium

**Comment by kaosat-dev** [comment]
Very good reads & points @jeromew ! Reading throught all that!
Having used both three.js & glmatrix I currently tend to lean towards glmatrix, with or without simd, because of its very simple & clear api, its optimisation levels, and the fact it is backed by typedArrays(/array like). I LOVE the fact you can just use arrays, and that mutation is handled carefully & explicitely
Only thing I am not a fan of is the verbosity sometimes (the 'out' parameter), but in the end it forced me to think things through more.
Also I love its small size (I regularly use [gl-mat4](https://github.com/stackgl/gl-mat4), gl-vec3 etc from [stack.gl](http://stack.gl/packages/) which are just package with specific parts of gl-matrix.

I have to ask around on the wasm side of things, if that is indeed a dud that would be a huge dissapointment !

btw just checked: ```new CSG.Vector3D``` is used quite extensively , mostly in the serializers & deserializers, but not so much in the 'core' but that might be hidden by the fact that csg.js creates Vertex3D instances which contain vector3Ds.

**Comment by jeromew** [comment]
I would think that it is too early to go all-in on wasm at this point + I have no idea how the open source community will react to wasm so this is a bet on developer mindshare. Maybe it is better to go towards csg.js beeing "port to wasm ready" (whatever that could mean) rather than go direcly to wasm. Especially since there is probably room for improvement in the current code base.

**Comment by kaosat-dev** [comment]
I am honestly not for or against wasm at this stage, I just consider it a very interesting option to explore further.
I still think that we need to have performance tests (#33) in addition to better unit test coverage so that we can compare performance of implementations.

**Comment by z3dev** [comment]
I was actually starting down the road of re-implementing Vector2D and Vector3D as arrays. But stopped because we (a) didn't have performance tests, and (b) didn't know our test coverage. We have (b) now but need more test cases to complete a nice test suite.

I didn't see much advantage of using glMatrix but liked the API. I may need to revisit this library again.

**Comment by z3dev** [comment]
V2 implements vector2 and vector3 with simple arrays and math, following GL-MATRIX.

Closing this issue.
