### ISSUE TITLE
API document error

### ISSUE THREAD

**Issue by aleung** [jscad/csg.js#98]
In https://github.com/jscad/csg.js/blob/master/docs/api.md, there are duplicated functions of `cube`, `sphere`, `cylinder`. For example: [cube](https://github.com/jscad/csg.js/blob/master/docs/api.md#cubeoptions--csg) and [cube](https://github.com/jscad/csg.js/blob/master/docs/api.md#cubeoptions--csg-1)

It looks like part of them are instance method of `CSG` rather than global function.

**Comment by kaosat-dev** [comment]
Hi @aleung 
This is intentional : for now there are two very similar but NOT identical APIs (as you have noticed), we are currently working on deprecating those attached to CSG/CAG objects (not instance methods btw, just attached to the CSG/CAG objects).
If you want to use the future facing api , please use that are not attached to CSG/CAG.
There are also a few discussions going on here on Github about the API changes:
https://github.com/jscad/csg.js/issues/96
and
https://github.com/jscad/OpenJSCAD.org/issues/323

**Comment by aleung** [comment]
@kaosat-dev Thanks. I was confused by various APIs provided by JSCAD for the same purpose and your answer make me clear.

Some CSG API looks powerful than function API. For example, `CSG.cube` accepts a `center` parameter to save a `translate`. Will features like it will be added into function API?

**Comment by z3dev** [comment]
We would like to address documentation issues in V2. Let’s see...

**Comment by z3dev** [comment]
@aleung V2 JSCAD is now available at www.jscad.xyz

The API is 100% functional now, and documented at www.jscad.xyz/docs/

Please try V2 and let us know if there are any problems.
